export const REGISTRATION_USER = 'REGISTRATION_USER'
export const SEND_MONEY = 'SEND_MONEY'

export const POST_PENDING = 'POST_PENDING'

export const GET_CONFIG = 'GET_CONFIG'

export const GET_TRANSACTION_HISTORY = 'GET_TRANSACTION_HISTORY'

export const GET_ALL_BALANCE_INFO = 'GET_ALL_BALANCE_INFO'
export const GET_WORK = 'GET_WORK'

/* Reset store */
export const APP_RESET = 'APP_RESET'
